name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        zip coverage.zip htmlcov/ xml-coverage/ .coverage

    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: htmlcov-${{ matrix.python-version }}
        path: htmlcov